name: ttttv_flutter
description: Flutter client for TTTTV.
publish_to: none
version: 0.3.7+10

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  brotli: ^0.6.0
  crypto: ^3.0.6
  dio: ^5.8.0+1
  file_picker: ^10.3.2
  fixnum: ^1.1.1
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  protobuf: ^3.1.0
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  web_socket_channel: ^3.0.3
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
  window_manager: ^0.4.3
  flutter_js: 0.8.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vod/sources.json
